FROM openjdk:11-jre-alpine
VOLUME /tmp

ARG JAR_FILE=api/build/libs/app.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar", "-Dprofile=docker"]
