FROM openjdk:8-jre-alpine
VOLUME /tmp

ARG JAR_FILE=api/build/libs/api.jar
COPY ${JAR_FILE} api.jar

EXPOSE 8080

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/api.jar", "-Dprofile=docker"]
